
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutNavbar': typeof import("../components/AboutNavbar.vue")['default']
    'ButtonLink': typeof import("../components/ButtonLink.vue")['default']
    'Dropdown': typeof import("../components/Dropdown.vue")['default']
    'FileDownload': typeof import("../components/FileDownload.vue")['default']
    'Footer': typeof import("../components/Footer.vue")['default']
    'Header': typeof import("../components/Header.vue")['default']
    'HonorCard': typeof import("../components/HonorCard.vue")['default']
    'LoginComponent': typeof import("../components/LoginComponent.vue")['default']
    'Navbar': typeof import("../components/Navbar.vue")['default']
    'PageHeader': typeof import("../components/PageHeader.vue")['default']
    'PaginationComponent': typeof import("../components/PaginationComponent.vue")['default']
    'SelectionRules': typeof import("../components/SelectionRules.vue")['default']
    'StudentApply': typeof import("../components/StudentApply.vue")['default']
    'Table': typeof import("../components/Table.vue")['default']
    'Tabs': typeof import("../components/Tabs/index.vue")['default']
    'TabsItem': typeof import("../components/Tabs/item.vue")['default']
    'UpdatePassword': typeof import("../components/UpdatePassword.vue")['default']
    'NuxtWelcome': typeof import("../../../../../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../../../../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../../../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'Icon': typeof import("../../../../../node_modules/nuxt-icon/dist/runtime/components/index")['default']
    'NuxtScrollbar': typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
    'Swiper': typeof import("swiper/vue")['Swiper']
    'SwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'NuxtPage': typeof import("../../../../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutNavbar': typeof import("../components/AboutNavbar.vue")['default']
    'LazyButtonLink': typeof import("../components/ButtonLink.vue")['default']
    'LazyDropdown': typeof import("../components/Dropdown.vue")['default']
    'LazyFileDownload': typeof import("../components/FileDownload.vue")['default']
    'LazyFooter': typeof import("../components/Footer.vue")['default']
    'LazyHeader': typeof import("../components/Header.vue")['default']
    'LazyHonorCard': typeof import("../components/HonorCard.vue")['default']
    'LazyLoginComponent': typeof import("../components/LoginComponent.vue")['default']
    'LazyNavbar': typeof import("../components/Navbar.vue")['default']
    'LazyPageHeader': typeof import("../components/PageHeader.vue")['default']
    'LazyPaginationComponent': typeof import("../components/PaginationComponent.vue")['default']
    'LazySelectionRules': typeof import("../components/SelectionRules.vue")['default']
    'LazyStudentApply': typeof import("../components/StudentApply.vue")['default']
    'LazyTable': typeof import("../components/Table.vue")['default']
    'LazyTabs': typeof import("../components/Tabs/index.vue")['default']
    'LazyTabsItem': typeof import("../components/Tabs/item.vue")['default']
    'LazyUpdatePassword': typeof import("../components/UpdatePassword.vue")['default']
    'LazyNuxtWelcome': typeof import("../../../../../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../../../../../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../../../../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyIcon': typeof import("../../../../../node_modules/nuxt-icon/dist/runtime/components/index")['default']
    'LazyNuxtScrollbar': typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
    'LazySwiper': typeof import("swiper/vue")['Swiper']
    'LazySwiperSlide': typeof import("swiper/vue")['SwiperSlide']
    'LazyNuxtPage': typeof import("../../../../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutNavbar: typeof import("../components/AboutNavbar.vue")['default']
export const ButtonLink: typeof import("../components/ButtonLink.vue")['default']
export const Dropdown: typeof import("../components/Dropdown.vue")['default']
export const FileDownload: typeof import("../components/FileDownload.vue")['default']
export const Footer: typeof import("../components/Footer.vue")['default']
export const Header: typeof import("../components/Header.vue")['default']
export const HonorCard: typeof import("../components/HonorCard.vue")['default']
export const LoginComponent: typeof import("../components/LoginComponent.vue")['default']
export const Navbar: typeof import("../components/Navbar.vue")['default']
export const PageHeader: typeof import("../components/PageHeader.vue")['default']
export const PaginationComponent: typeof import("../components/PaginationComponent.vue")['default']
export const SelectionRules: typeof import("../components/SelectionRules.vue")['default']
export const StudentApply: typeof import("../components/StudentApply.vue")['default']
export const Table: typeof import("../components/Table.vue")['default']
export const Tabs: typeof import("../components/Tabs/index.vue")['default']
export const TabsItem: typeof import("../components/Tabs/item.vue")['default']
export const UpdatePassword: typeof import("../components/UpdatePassword.vue")['default']
export const NuxtWelcome: typeof import("../../../../../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../../../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../../../../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const Icon: typeof import("../../../../../node_modules/nuxt-icon/dist/runtime/components/index")['default']
export const NuxtScrollbar: typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
export const Swiper: typeof import("swiper/vue")['Swiper']
export const SwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const NuxtPage: typeof import("../../../../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutNavbar: typeof import("../components/AboutNavbar.vue")['default']
export const LazyButtonLink: typeof import("../components/ButtonLink.vue")['default']
export const LazyDropdown: typeof import("../components/Dropdown.vue")['default']
export const LazyFileDownload: typeof import("../components/FileDownload.vue")['default']
export const LazyFooter: typeof import("../components/Footer.vue")['default']
export const LazyHeader: typeof import("../components/Header.vue")['default']
export const LazyHonorCard: typeof import("../components/HonorCard.vue")['default']
export const LazyLoginComponent: typeof import("../components/LoginComponent.vue")['default']
export const LazyNavbar: typeof import("../components/Navbar.vue")['default']
export const LazyPageHeader: typeof import("../components/PageHeader.vue")['default']
export const LazyPaginationComponent: typeof import("../components/PaginationComponent.vue")['default']
export const LazySelectionRules: typeof import("../components/SelectionRules.vue")['default']
export const LazyStudentApply: typeof import("../components/StudentApply.vue")['default']
export const LazyTable: typeof import("../components/Table.vue")['default']
export const LazyTabs: typeof import("../components/Tabs/index.vue")['default']
export const LazyTabsItem: typeof import("../components/Tabs/item.vue")['default']
export const LazyUpdatePassword: typeof import("../components/UpdatePassword.vue")['default']
export const LazyNuxtWelcome: typeof import("../../../../../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../../../../../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../../../../../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyIcon: typeof import("../../../../../node_modules/nuxt-icon/dist/runtime/components/index")['default']
export const LazyNuxtScrollbar: typeof import("../node_modules/@davestewart/nuxt-scrollbar/dist/runtime/NuxtScrollbar.vue")['default']
export const LazySwiper: typeof import("swiper/vue")['Swiper']
export const LazySwiperSlide: typeof import("swiper/vue")['SwiperSlide']
export const LazyNuxtPage: typeof import("../../../../../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
